---
- hosts: localhost
  become: true
  vars:
    root: /Users/dev/Projects/Workspaces/WardrobeManagerDeployment/
    ansible_python_interpreter: /opt/homebrew/bin/python3

  tasks:
  - name: Log into DockerHub
    docker_login:
      username: trekcampy
      password: cobra123

  - name: create docker image after building repo
    command: docker build -t wmms . --no-cache=true 
    args:
      chdir: "{{ root }}dockerizers/wm"

  - name: tag docker image
    command: docker tag wmms:latest trekcampy/wmms:latest

  - name: push docker image to docker hub
    command: docker push trekcampy/wmms:latest 

  - name: remove image from local server
    command: docker rmi wmms:latest trekcampy/wmms:latest

  - name: delete the application
    command: kubectl delete -f "{{ root }}"kube/wmms/wmms-deployment-5-with-vol.yml

  - name: deploy the application
    command: kubectl apply -f "{{ root }}"kube/wmms/wmms-deployment-5-with-vol.yml

  - name: enable wmms service
    command: kubectl apply -f "{{ root }}"kube/wmms/wmms-service-nodeport.yml
