---
- hosts: localhost
  become: true

  tasks:
  - name: create docker image after building repo
    command: docker build -t ltt . 
    args:
      chdir: /Users/dev/Projects/Workspaces/WardrobeManagerDeployment/dockerizers/ltt

  - name: tag docker image
    command: docker tag ltt:latest trekcampy/ltt:latest

  - name: push docker image to docker hub
    command: docker push trekcampy/ltt:latest 

  - name: remove image from local server
    command: docker rmi ltt:latest trekcampy/ltt:latest
