apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-standalone
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        selector: redis-standalone
    spec:
      containers:
      - name: redis-standalone
        image: redis:6.2.4
---