---
- hosts: localhost
  become: true

  tasks:
  - name: create docker image after building repo
    command: docker build -t um . 
    args:
      chdir: /Users/dev/Projects/Workspaces/WardrobeManagerDeployment/dockerizers/um

  - name: tag docker image
    command: docker tag um:latest trekcampy/um:latest

  - name: push docker image to docker hub
    command: docker push trekcampy/um:latest 

  - name: remove image from local server
    command: docker rmi um:latest trekcampy/um:latest
