apiVersion: v1
kind: Service
metadata:
  name: umms
  labels:
    app: umms
spec:
  type: NodePort
  selector:
    app: umms
  ports:
  - protocol: TCP
    port: 57400
    targetPort: 57400
    nodePort: 30000
