apiVersion: v1
kind: Service
metadata:
  name: wmms-lb-service
  labels:
    app: wmms
spec:
  type: LoadBalancer
  selector:
    app: wmms
  ports:
  - protocol: TCP
    port: 57401 
    targetPort: 57401
  externalIPs:
  - 172.16.42.31
