apiVersion: v1
kind: Service
metadata:
  name: wmms
  labels:
    app: wmms
spec:
  type: NodePort
  selector:
    app: wmms
  ports:
  - protocol: TCP
    port: 57401
    targetPort: 57401
    nodePort: 30001
